### ISSUE TITLE
[Feature Request] Repo Update to 20.04 LTS

### ISSUE THREAD

**Issue by ueslai** [xapienz/curl-debian-scripts#1]
Would you be able to update your repo to include 20.04 LTS? Thanks!

**Comment by xapienz** [comment]
Thanks for your interest! I will work in this

**Comment by xapienz** [comment]
Implemented:
https://github.com/xapienz/curl-debian-scripts/commit/3a4746725bb33836f377fe009c3b0e6049ed24df
https://launchpad.net/~xapienz/+archive/ubuntu/curl34/+sourcepub/11333971/+listing-archive-extra
