### ISSUE TITLE
This package is not working anymore

### ISSUE THREAD

**Issue by lonormaly** [xapienz/curl-debian-scripts#2]
This package is not working anymore. 
Up until a month ago it worked like a charm, now for some reason it stopped working
/usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/lib/libs3.so.2)

**Comment by xapienz** [comment]
I suspect the problem is not in the package. Ubuntu updated their packages, and your OS upgraded to Ubuntu's original versions.
As I am not Ubuntu employee and I am not able to immediately support all Ubuntu upgrades, I suggest to downgrade the package and lock the version, so it won't get upgraded automatically.

You may see available package versions here (use "Published in" filter to choose Ubuntu version): https://launchpad.net/~xapienz/+archive/ubuntu/curl34, or you can use `apt-cache policy libcurl4` to see available versions.

After that, do:
```
sudo apt-get install curl=<version> libcurl4=<version>
sudo apt-mark hold curl libcurl4
```
Where `<version>` is currently `7.58.0-2ubuntu3.8ppa2` for Bionic, and other value for other versions.

Meanwhile, I will work on updating the packages in my ppa soon.

**Comment by lonormaly** [comment]
Thanks a lot! it worked like a charm! Will love to hear on when you update the packages

**Comment by lonormaly** [comment]
On a fresh install I get 
E: Version '7.58.0-2ubuntu3.8ppa2' for 'libcurl4' was not found
How can I download this version?

**Comment by xapienz** [comment]
> How can I download this version?

The reason why it's not found is either PPA is not added, or another Ubuntu version is used.
So you may try all steps:
```
# add ppa:
sudo add-apt-repository ppa:xapienz/curl34
sudo apt-get update

# check available versions and find correct version:
sudo apt-cache policy libcurl4

# install the packages:
sudo apt-get install curl=<version> libcurl4=<version>
```

**Comment by lonormaly** [comment]
You're genius! Thank you so much <3

**Comment by xapienz** [comment]
Great that it worked!

**Comment by xapienz** [comment]
Btw, I updated the packages for Bionic and Focal

**Comment by lonormaly** [comment]
GREAT! I saw! Thanks a lot

**Comment by lonormaly** [comment]
@xapienz Hey, this package is broken again :(( Every how often will it break?
That's the only package that's allowed to be installed: 7.58.0-2ubuntu3.12ppa2
But curl34 doesn't seem to have this version... That's frustrating - our whole servers can't run without it... What can we do to secure future changes? How can we make it work with curl34?

Thanks

**Comment by lonormaly** [comment]
@xapienz Hey, this package is broken again :(( Every how often will it break?
That's the only package that's allowed to be installed: 7.58.0-2ubuntu3.12ppa2
But curl34 doesn't seem to have this version... That's frustrating - our whole servers can't run without it... What can we do to secure future changes? How can we make it work with curl34?

Thanks

**Comment by xapienz** [comment]
@lonormaly
Ubuntu released new version of curl, and I didn't update the packages yet.
You can downgrade curl to 7.58.0-2ubuntu3.12ppa2, and it will work again.

> What can we do to secure future changes?

You can use `apt-mark hold <package name>` to prevent the package from from automatic upgrades.

**Comment by lonormaly** [comment]
Thanks for the rapid reply :)

1. how can we downgrade to 7.58.0-2ubuntu3.12ppa2?
2. The problem with hold is that every time we install the lib is when we run a new server with fresh / latest build of Bionic (latest updates of libs). If there’s a way to force installation of this version it can help tremendously.

Thanks

**Comment by xapienz** [comment]
> how can we downgrade to 7.58.0-2ubuntu3.12ppa2?

It can be done by using the command `sudo apt install <package>=<version>`.
So I guess it can be like `sudo apt install curl=7.58.0-2ubuntu3.12ppa2 libcurl4=7.58.0-2ubuntu3.12ppa2 libcurl3-gnutls=7.58.0-2ubuntu3.12ppa2 libcurl4-openssl-dev=7.58.0-2ubuntu3.12ppa2`, depending on the packages which you use.

**Comment by xapienz** [comment]
Hello,
I implemented another approach to prevent undesirable autoupdates, if having curl3+4 solution is more important than updates from upstream ubuntu.
Here it is: https://github.com/xapienz/curl-debian-scripts/commit/e8e54c67e61439289455d25c2d928c492e41737d

You may install the package `curl34` (`sudo apt install curl34`), and it will force ppa version of `libcurl4`.
In case if Ubuntu update arrives, `libcurl4` will not be updated by `sudo apt upgrade` (however, `sudo apt dist-upgrade` will suggest to uninstall `curl34` and upgrade `libcurl4`).
So installing `curl34` will lock packages to ppa.

Let me know if this works for you.

Also, I updated the ppa to last versions.
